version: "3"
services: 
  implement_go:
    image: basic:1.4
    ports: 
    - 8080:8080
    env_file:
     - .env
    restart: always
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - basic
  mysqldb:
    image: mysql:latest
    env_file:
     - .env
    ports:
      - 3305:3306
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost","-u","root","-p $MYSQL_ROOT_PASSWORD"]
          timeout: 20s
          retries: 10
    networks:
    - basic

networks:
  basic:
    driver: bridge
    